
-- local 事件 = {
--     名称 = '御前科举',
--     是否打开 = true,
--     开始时间 = os.time { year = 2022, month = 7, day = 25, hour = 0, min = 0, sec = 00 },
--     结束时间 = os.time { year = 2025, month = 7, day = 30, hour = 0, min = 0, sec = 00 }
-- }

-- function 事件:事件初始化()
--     self.NPC = {}
--     self.活动开始 = false
--     self.测试刷怪 = function(玩家, a, b)
--         self:刷出NPC() --todo 测试用
--     end

-- end

-- local _开启日 = { --true开启--false
--     ["1"] = true,
--     ["2"] = true,
--     ["3"] = true,
--     ["4"] = true,
--     ["5"] = true,
--     ["6"] = true,
--     ["0"] = true,
-- }

-- end

-- local _主怪信息 = {
--     { 名称 = '科举报名官员', 脚本 = 'scripts/npc/御前科举/科举报名官员.lua', 外形 = 3085,
--         mid = 1003, X = 95, Y = 25,
--         方向 = 1
--     },
--     { 名称 = '乡试考官1号', 序列 = 1, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 300, Y = 250,
--         方向 = 1
--     },
--     { 名称 = '乡试考官2号', 序列 = 2, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 160, Y = 210,
--         方向 = 1
--     },
--     { 名称 = '乡试考官3号', 序列 = 3, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 75, Y = 250,
--         方向 = 1
--     },
--     { 名称 = '乡试考官4号', 序列 = 4, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 90, Y = 150,
--         方向 = 1
--     },
--     { 名称 = '乡试考官5号', 序列 = 5, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 110, Y = 95,
--         方向 = 1
--     },
--     { 名称 = '乡试考官6号', 序列 = 6, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 80, Y = 10,
--         方向 = 1
--     },
--     { 名称 = '乡试考官7号', 序列 = 7, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 230, Y = 15,
--         方向 = 1
--     },
--     { 名称 = '乡试考官8号', 序列 = 8, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 330, Y = 30,
--         方向 = 1
--     },
--     { 名称 = '乡试考官9号', 序列 = 9, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 90, Y = 170,
--         方向 = 1
--     },
--     { 名称 = '乡试考官10号', 序列 = 10, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 190, Y = 210,
--         方向 = 1
--     },
--     { 名称 = '乡试考官11号', 序列 = 11, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 325, Y = 145,
--         方向 = 1
--     },
--     { 名称 = '乡试考官12号', 序列 = 12, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 405, Y = 180,
--         方向 = 1
--     },
--     { 名称 = '乡试考官13号', 序列 = 13, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 155, Y = 130,
--         方向 = 1
--     },
--     { 名称 = '乡试考官14号', 序列 = 14, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 45, Y = 120,
--         方向 = 1
--     },
--     { 名称 = '乡试考官15号', 序列 = 15, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 250, Y = 80,
--         方向 = 1
--     },
--     { 名称 = '乡试考官16号', 序列 = 16, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 450, Y = 90,
--         方向 = 1
--     },
--     { 名称 = '乡试考官17号', 序列 = 17, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1236, X = 220, Y = 20,
--         方向 = 1
--     },
--     { 名称 = '乡试考官18号', 序列 = 18, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 290, Y = 50,
--         方向 = 1
--     },
--     { 名称 = '乡试考官19号', 序列 = 19, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 265, Y = 110,
--         方向 = 1
--     },
--     { 名称 = '乡试考官20号', 序列 = 20, 脚本 = 'scripts/npc/御前科举/乡试考官.lua', 外形 = 3085,
--         mid = 1001, X = 330, Y = 250,
--         方向 = 1
--     },
--     { 名称 = '礼部省试官员', 脚本 = 'scripts/npc/御前科举/礼部省试官员.lua', 外形 = 3035,
--         mid = 1003, X = 115, Y = 60,
--         方向 = 1
--     },
--     { 名称 = '礼部省试官员', 脚本 = 'scripts/npc/御前科举/礼部省试官员.lua', 外形 = 3035,
--         mid = 1003, X = 145, Y = 45,
--         方向 = 1
--     },
--     { 名称 = '礼部省试官员', 脚本 = 'scripts/npc/御前科举/礼部省试官员.lua', 外形 = 3035,
--         mid = 1003, X = 65, Y = 45,
--         方向 = 1
--     },
--     { 名称 = '礼部省试官员', 脚本 = 'scripts/npc/御前科举/礼部省试官员.lua', 外形 = 3035,
--         mid = 1003, X = 135, Y = 10,
--         方向 = 1
--     },


-- }


-- function 事件:刷出NPC()
--     清空殿试报名数据()
--     清空科举排行数据()
--     self.活动开始 = true
--     for _, v in pairs(_主怪信息) do
--         local map = self:取地图(v.mid)
--         local NPC =
--         map:添加NPC {
--             名称 = v.名称,
--             外形 = v.外形,
--             序列 = v.序列,
--             时间 = 14400,
--             任务类型 = '御前科举',
--             脚本 = v.脚本,
--             X = v.X,
--             Y = v.Y,
--         }
--         table.insert(self.NPC, NPC)
--     end
--     self:发送系统("#G奉唐王之命，举办御前科举招才纳贤。天下所有有志之士都可以来我这报名。名列前茅者唐王重重有赏。#32")
--     self.能否报名 = true
-- end

-- function 事件:更新()
--     return not self.是否结束 and 900000
-- end

-- function 事件:是否在开启()
--     local 星期 = os.date("%w", os.time())
--     if _开启日[星期] then
--         local t = os.date("*t", os.time())
--         if (t.hour == 13 and t.min > 30) or (t.hour == 17 and t.min < 30) or (t.hour < 17 and t.hour > 13) then
--             return true
--         end
--     end
-- end


-- function 事件:是否在开启()
--     local t = os.date("*t", os.time())
--     if (t.hour == 10 and t.min > 30) or (t.hour == self.结束时 and t.min < self.结束分) or
--         (t.hour < self.结束时 and t.hour > 10) then
--         return true
--     end
-- end

-- function 事件:事件开始()
--     if self:是否在开启() then
--        self:清空事件NPC(self.名称)
--         self:刷出NPC()
--     end
-- end

-- function 事件:是否开启报名()
--     return self.能否报名
-- end

-- function 事件:是否开启殿试()
--     return self.能否殿试
-- end

-- function 事件:事件结束()
--     self.是否结束 = true
-- end

-- function 事件:整分处理(分钟, 小时, 星期)
--     if _开启日[星期] then
--         if 小时 == "13" and 分钟 == "30" then
--             self:清空事件NPC(self.名称)
--             self:刷出NPC()
--         elseif 小时 == "17" and 分钟 == "30" then
--             self.活动开始 = false --关闭
--             self:清空事件NPC(self.名称)
--             殿试用时排序()
--             保存殿试排名数据()
--         end
--     end
-- end

-- function 事件:整点处理(分钟, 小时, 星期)
--     if _开启日[星期] then
--         if 小时 == "16" then
--             省试用时排序()
--             self.能否报名 = false
--             self.能否殿试 = true
--         end
--     end
-- end

-- return 事件
